import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import Navbar from "@/components/Navbar";
import { Roboto } from "next/font/google";
import "react-tooltip/dist/react-tooltip.css";
import Footer from "@/components/Footer";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Shreeya Traditions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "relative")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
