import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import localFont from 'next/font/local'
import Navbar from "@/components/Navbar";

// const rubik = Rubik({ subsets: ["latin"] });
// Font files can be colocated inside of `pages`
const Calton = localFont({ src: '../public/fonts/Calton Elegance Sans-Regular.otf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(Calton.className, "relative")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
