import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { Roboto } from "next/font/google";
import 'react-tooltip/dist/react-tooltip.css'

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Shreeya Traditions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "relative")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
